import { StatData } from "@/components/Card/StatsCard";

export const statCardDataAdmin: StatData[] = [
  {
    id: "total-revenue",
    title: "Total Revenue",
    value: 345090,
    currency: "₹",
    type: "revenue",
    growth: {
      value: 20.5,
      label: "From last year",
      trend: "up",
    },
    tooltipContent: "Total revenue generated by events",
  },
  {
    id: "events-completed",
    title: "Events Completed",
    value: 65,
    type: "events",
    growth: {
      value: 5.1,
      label: "From last year",
      trend: "down",
    },
    tooltipContent: "Number of successfully completed events",
  },
  {
    id: "total-bookings",
    title: "Total Bookings",
    value: 3229,
    type: "bookings",
    growth: {
      value: 15.6,
      label: "From last year",
      trend: "up",
    },
    tooltipContent: "Total number of tickets booked",
  },
  {
    id: "total-organisers",
    title: "Total Organisers",
    value: 5,
    type: "organisers",
    date: `${new Date().toLocaleString("default", {
      month: "long",
    })}, ${new Date().getUTCFullYear()}`,
    tooltipContent: "Total number of event organisers onboarded",
  },
];
